version: '3.8'

services:
  spring-api:
    build:
      context: ./backend/simpleapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - backend_data:/app/data
    networks:
      - app-network
    depends_on:
      - database-postgres
    restart: unless-stopped

  database-postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  httpd:
    build:
      context: ./httpserver
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - spring-api
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  backend_data: